# Generated by Django 5.0.1 on 2024-02-16 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_billingaddress1_alter_order_billingcity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=250)),
                ('address_street', models.CharField(blank=True, max_length=200)),
                ('address_city', models.CharField(blank=True, max_length=200)),
                ('address_postcode', models.CharField(blank=True, max_length=200)),
                ('address_country', models.CharField(blank=True, max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Customer'), (2, 'Seller'), (3, 'Seller_admin'), (4, 'Sudo')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
