# Generated by Django 5.0.1 on 2024-02-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_profile_email_profile_address_houseno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='Active', max_length=10),
        ),
    ]
